services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4jpass
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=redis
      - REDIS_DB=0
    depends_on:
      - mongo
      - neo4j
      - redis

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  neo4j:
    image: neo4j:5.26.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4jpass
    volumes:
      - neo4j-data:/data
  
  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    command: ["redis-server", "--notify-keyspace-events", "ExgK"]

volumes:
  mongo-data: {}
  neo4j-data:

